spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
    add-properties: false
  cloud:
    consul:
      host: consul
      config:
        enabled: true
        format: YAML
        fail-fast: true
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 6
          max-interval: 5000
          multiplier: 1.5
      discovery:
        enabled: true
        register: true
        fail-fast: true
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 6
          max-interval: 5000
          multiplier: 1.5
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 15s
        health-check-timeout: 10s
        health-check-critical-timeout: 30s
        metadata:
          grpc-port: ${spring.grpc.server.port:9090}

management:
  tracing:
    sampling:
      probability: 0.1
  otlp:
    metrics:
      export:
        enabled: true
        url: http://lgtm:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          enabled: true
          endpoint: http://lgtm:4318/v1/traces
    logging:
      export:
        otlp:
          enabled: true
          endpoint: http://lgtm:4318/v1/logs

logging:
  level:
    br.com.jpbassinello.sbcgg: INFO
